INSERT INTO province_names (PROVINCE_ID, PROVINCE_NAME) VALUES
                                                            ('AB', 'Alberta'),
                                                            ('BC', 'British Columbia'),
                                                            ('MB', 'Manitoba'),
                                                            ('NB', 'New Brunswick'),
                                                            ('NL', 'Newfoundland and Labrador'),
                                                            ('NS', 'Nova Scotia'),
                                                            ('NT', 'Northwest Territories'),
                                                            ('NU', 'Nunavut'),
                                                            ('ON', 'Ontario'),
                                                            ('PE', 'Prince Edward Island'),
                                                            ('QC', 'Quebec'),
                                                            ('SK', 'Saskatchewan'),
                                                            ('YT', 'Yukon'),
                                                            ('CA', 'California'),
                                                            ('TX', 'Texas'),
                                                            ('FL', 'Florida'),
                                                            ('NY', 'New York'),
                                                            ('IL', 'Illinois'),
                                                            ('PA', 'Pennsylvania'),
                                                            ('OH', 'Ohio'),
                                                            ('MI', 'Michigan'),
                                                            ('GA', 'Georgia'),
                                                            ('NC', 'North Carolina'),
                                                            ('NJ', 'New Jersey'),
                                                            ('VA', 'Virginia'),
                                                            ('WA', 'Washington'),
                                                            ('AZ', 'Arizona'),
                                                            ('MA', 'Massachusetts'),
                                                            ('IN', 'Indiana'),
                                                            ('TN', 'Tennessee'),
                                                            ('MO', 'Missouri'),
                                                            ('MD', 'Maryland'),
                                                            ('WI', 'Wisconsin'),
                                                            ('CO', 'Colorado'),
                                                            ('MN', 'Minnesota'),
                                                            ('SC', 'South Carolina'),
                                                            ('AL', 'Alabama'),
                                                            ('LA', 'Louisiana'),
                                                            ('KY', 'Kentucky'),
                                                            ('OR', 'Oregon'),
                                                            ('OK', 'Oklahoma'),
                                                            ('CT', 'Connecticut'),
                                                            ('IA', 'Iowa'),
                                                            ('MS', 'Mississippi'),
                                                            ('AR', 'Arkansas'),
                                                            ('KS', 'Kansas'),
                                                            ('NV', 'Nevada'),
                                                            ('UT', 'Utah'),
                                                            ('NM', 'New Mexico'),
                                                            ('NE', 'Nebraska'),
                                                            ('WV', 'West Virginia'),
                                                            ('ID', 'Idaho'),
                                                            ('HI', 'Hawaii'),
                                                            ('MT', 'Montana'),
                                                            ('WY', 'Wyoming'),
                                                            ('ND', 'North Dakota'),
                                                            ('SD', 'South Dakota'),
                                                            ('AK', 'Alaska'),
                                                            ('VT', 'Vermont'),
                                                            ('NH', 'New Hampshire'),
                                                            ('ME', 'Maine');
