INSERT INTO DOCTORS (
    DOCTOR_ID, FIRST_NAME, LAST_NAME, SPECIALTY
) VALUES
      (1, 'John', 'Doe', 'Cardiologist'),
      (2, 'Jane', 'Smith', 'Neurologist'),
      (3, 'Michael', 'Johnson', 'Orthopedic Surgeon'),
      (4, 'Emily', 'Williams', 'Pediatrician'),
      (5, 'David', 'Brown', 'Dermatologist'),
      (6, 'Sarah', 'Jones', 'Oncologist'),
      (7, 'Robert', 'Garcia', 'Endocrinologist'),
      (8, 'Linda', 'Martinez', 'Radiologist'),
      (9, 'William', 'Davis', 'Surgeon'),
      (10, 'Olivia', 'Miller', 'Internal Medicine'),
      (11, 'James', 'Wilson', 'Urologist'),
      (12, 'Sophia', 'Moore', 'Gastroenterologist'),
      (13, 'Daniel', 'Taylor', 'Ophthalmologist'),
      (14, 'Ava', 'Anderson', 'Psychiatrist'),
      (15, 'Matthew', 'Thomas', 'Gynecologist'),
      (16, 'Isabella', 'Harris', 'Nephrologist'),
      (17, 'Christopher', 'Clark', 'Rheumatologist'),
      (18, 'Mia', 'Lewis', 'Pulmonologist'),
      (19, 'Joseph', 'Walker', 'Family Medicine'),
      (20, 'Charlotte', 'Hall', 'Hematologist'),
      (21, 'Ethan', 'Allen', 'Emergency Medicine'),
      (22, 'Amelia', 'Young', 'Allergist'),
      (23, 'Benjamin', 'King', 'General Surgeon'),
      (24, 'Harper', 'Wright', 'Anesthesiologist'),
      (25, 'Jackson', 'Scott', 'Cardiothoracic Surgeon'),
      (26, 'Ella', 'Torres', 'Plastic Surgeon'),
      (27, 'Henry', 'Nguyen', 'Orthopedic Surgeon'),
      (28, 'Sofia', 'Adams', 'Infectious Disease Specialist'),
      (29, 'Lucas', 'Baker', 'Obstetrician'),
      (30, 'Aria', 'Nelson', 'Vascular Surgeon'),
      (31, 'Alexander', 'Mitchell', 'Neurosurgeon'),
      (32, 'Chloe', 'Perez', 'Endocrinologist'),
      (33, 'Liam', 'Roberts', 'Geriatrician'),
      (34, 'Lily', 'Carter', 'Sports Medicine Specialist'),
      (35, 'Aiden', 'Murphy', 'Emergency Medicine'),
      (36, 'Zoe', 'Gonzalez', 'Clinical Pharmacologist'),
      (37, 'Mason', 'Ramirez', 'Pediatric Surgeon'),
      (38, 'Nora', 'Cooper', 'Rheumatologist'),
      (39, 'Eli', 'Howard', 'Cardiologist'),
      (40, 'Mila', 'Bailey', 'Gastroenterologist'),
      (41, 'Leo', 'Morris', 'Hematologist'),
      (42, 'Charlotte', 'Kelly', 'Neurologist'),
      (43, 'Oliver', 'Howard', 'Urologist'),
      (44, 'Sophie', 'Ward', 'Oncologist'),
      (45, 'Daniel', 'Murphy', 'Plastic Surgeon'),
      (46, 'Grace', 'James', 'Family Medicine'),
      (47, 'James', 'Walker', 'Internal Medicine'),
      (48, 'Ella', 'Lee', 'Surgeon'),
      (49, 'Logan', 'Collins', 'Gynecologist'),
      (50, 'Mia', 'Mitchell', 'Pulmonologist');
